# Generated by Django 4.2.3 on 2023-09-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nme',
            new_name='name',
        ),
    ]
